# Background and foreground colors
background = #343434
foreground = #cccccc

# Standard colors
palette = 0=#343434
palette = 1=#af7150
palette = 2=#8a766c
palette = 3=#b47664
palette = 4=#a78854
palette = 5=#918775
palette = 6=#b89268
palette = 7=#a8a8a8

# Bright colors
palette = 8=#818181
palette = 9=#c59981
palette = 10=#ab9b92
palette = 11=#cba095
palette = 12=#c0a982
palette = 13=#b1aa9c
palette = 14=#d0b598
palette = 15=#cccccc
